on:
  workflow_dispatch:  # to enables the "Run workflow" button

name: Deploy .NET App to Windows EC2

on:
  push:
    branches: [ZL-work]
  paths:
      - 'backend/**' 
jobs:
  deploy-backend:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET App
      run: dotnet publish -c Release -o published

    - name: Copy files to EC2 via WinRM
      uses: mcmilk/pswinrm-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        user: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        command: |
          mkdir C:\test\app -Force
          Remove-Item -Recurse -Force C:\test\app\* -ErrorAction SilentlyContinue

    - name: Transfer published app to EC2
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./published/
        remote: C:/test/app/
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}

    - name: Start app on EC2
      uses: mcmilk/pswinrm-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        user: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        command: |
          # Kill any existing dotnet process that runs CourseService
          Get-Process -Name "CourseService" -ErrorAction SilentlyContinue | Stop-Process -Force

          Start-Process "dotnet" -ArgumentList "C:\test\app\CourseService.dll --urls http://0.0.0.0:5000" -WindowStyle Hidden
